// Demo seed: loaded once when localStorage is empty so charts are not blank.
const now = Date.now()
const day = 24 * 60 * 60 * 1000

export const mockDeals = [
  {
    id: 'demo-1',
    datetime: new Date(now - 9 * day).toISOString(),
    type: 'buy',
    asset: 'USDT',
    fiat: 'RUB',
    amount: 1000,
    price: 92.5,
    fee: 0,
    platform: 'Bybit',
    counterparty: 'Алишер',
    notes: 'Демо: закуп под продажу',
  },
  {
    id: 'demo-2',
    datetime: new Date(now - 8 * day).toISOString(),
    type: 'sell',
    asset: 'USDT',
    fiat: 'RUB',
    amount: 1000,
    price: 94.1,
    fee: 100,
    platform: 'Tinkoff',
    counterparty: 'Алишер',
    notes: 'Демо: продажа +спред',
  },
  {
    id: 'demo-3',
    datetime: new Date(now - 6 * day).toISOString(),
    type: 'buy',
    asset: 'BTC',
    fiat: 'USD',
    amount: 0.05,
    price: 67200,
    fee: 5,
    platform: 'Binance',
    counterparty: 'Ольга',
    notes: 'Демо',
  },
  {
    id: 'demo-4',
    datetime: new Date(now - 5 * day).toISOString(),
    type: 'sell',
    asset: 'BTC',
    fiat: 'USD',
    amount: 0.05,
    price: 68900,
    fee: 5,
    platform: 'Bybit',
    counterparty: 'Ольга',
    notes: 'Демо: фиксация',
  },
  {
    id: 'demo-5',
    datetime: new Date(now - 4 * day).toISOString(),
    type: 'buy',
    asset: 'USDT',
    fiat: 'KZT',
    amount: 2500,
    price: 495,
    fee: 0,
    platform: 'Cash',
    counterparty: 'Наличка Астана',
    notes: 'Демо',
  },
  {
    id: 'demo-6',
    datetime: new Date(now - 3 * day).toISOString(),
    type: 'sell',
    asset: 'USDT',
    fiat: 'KZT',
    amount: 2500,
    price: 501.5,
    fee: 2000,
    platform: 'Cash',
    counterparty: 'Наличка Астана',
    notes: 'Демо',
  },
  {
    id: 'demo-7',
    datetime: new Date(now - 2 * day).toISOString(),
    type: 'buy',
    asset: 'SOL',
    fiat: 'USD',
    amount: 12,
    price: 172.4,
    fee: 2,
    platform: 'Bybit',
    counterparty: 'Маркет',
    notes: 'Демо',
  },
  {
    id: 'demo-8',
    datetime: new Date(now - 1 * day).toISOString(),
    type: 'sell',
    asset: 'ETH',
    fiat: 'RUB',
    amount: 0.8,
    price: 312000,
    fee: 300,
    platform: 'Sber',
    counterparty: 'Игорь',
    notes: 'Демо',
  },
]

export const mockRatings = {
  Алишер: { rating: 5, note: 'Быстрые переводы' },
  Ольга: { rating: 4, note: '' },
}
